# Generated by Django 4.1.1 on 2022-09-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=50)),
                ('cust_email', models.CharField(max_length=50)),
                ('cust_phone', models.BigIntegerField()),
                ('cust_img', models.ImageField(upload_to='customer/')),
                ('cust_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=50)),
                ('seller_email', models.CharField(max_length=50)),
                ('seller_phone', models.BigIntegerField()),
                ('seller_img', models.ImageField(upload_to='seller/')),
                ('seller_password', models.CharField(max_length=50)),
            ],
        ),
    ]
